### ISSUE TITLE
login error on linux (mongodb has started )

### ISSUE THREAD

**Issue by Hellowor1d** [Ma63d/kov-blog#17]
system: linuxmint 
db: sudo service mongod start  //(has started)
when  I click the button to login:

TypeError: Failed to fetch                       
Uncaught (in promise) TypeError: Cannot read property 'error' of undefined              
    at eval (eval at <anonymous> (app.js:1341), <anonymous>:39:46)

I'm new to vuex ,dont know what caused the err
![_039](https://cloud.githubusercontent.com/assets/10154292/25167041/806c9f0a-2510-11e7-8df1-9d17f668a82b.jpg)

**Comment by Ma63d** [comment]
Recently, I've received msg from another user of kov-blog telling me the same error too. And I'm absolutely sure the problem is that either you **did not** run the server or the server running failed, which maybe caused by mongodb connection error. 
If you already run `npm run dev-server` in your terminal, you will find in the terminal output that the server start failed,then try to restart , and then fail again, constantly. So, maybe you didn't install mongodb, something wrong happens when installing or you changed the port of mongodb. 
Run `mongo` for more detail.

**Comment by Hellowor1d** [comment]
@Ma63d  
Actually you're right.
Thanks a lot for your reply ! 
and `kov-blog` is a wonderful repo to learn koa & vue project :+1:
(Uh...may I have your Wechat for better communication ?sincerely~)

**Comment by Ma63d** [comment]
@Hellowor1d 
Thx. So honored to hear that kov-blog helps some front end learners.
My email is chuck7liu#gmail.com. Let 's  contact with email about wechat acct.

**Comment by Hellowor1d** [comment]
great !  now you can close the issue and I have sent email to you
